' Generated by Instant-Layout PDF Importer
Dim designer, layout, obj
Set designer = CreateObject("GMCInspireDesigner.Application")
Set layout = designer.ActiveDocument.ActiveLayout

Set obj = layout.CreateObject(1, "Text_1")
obj.X = 12.32
obj.Y = 9.76
obj.Width = 2.88
obj.Height = 5.76
obj.Content = "Form"

Set obj = layout.CreateObject(1, "Text_2")
obj.X = 15.24
obj.Y = 7.27
obj.Width = 19.00
obj.Height = 10.17
obj.Content = "1040 "

Set obj = layout.CreateObject(1, "Text_3")
obj.X = 105.10
obj.Y = 8.27
obj.Width = 8.92
obj.Height = 8.90
obj.Content = "20"

Set obj = layout.CreateObject(1, "Text_4")
obj.X = 114.02
obj.Y = 8.54
obj.Width = 9.42
obj.Height = 8.36
obj.Content = "25"

Set obj = layout.CreateObject(1, "Text_5")
obj.X = 34.42
obj.Y = 11.65
obj.Width = 65.69
obj.Height = 5.01
obj.Content = "U.S. Individual Income Tax Return "

Set obj = layout.CreateObject(1, "Text_6")
obj.X = 34.42
obj.Y = 9.04
obj.Width = 52.13
obj.Height = 2.47
obj.Content = "Department of the Treasury—Internal Revenue Service "

Set obj = layout.CreateObject(1, "Text_7")
obj.X = 125.67
obj.Y = 13.17
obj.Width = 22.92
obj.Height = 2.88
obj.Content = "OMB No. 1545-0074"

Set obj = layout.CreateObject(1, "Text_8")
obj.X = 152.43
obj.Y = 13.60
obj.Width = 48.72
obj.Height = 2.47
obj.Content = "IRS Use Only—Do not write or staple in this space. "

Set obj = layout.CreateObject(1, "Text_9")
obj.X = 12.70
obj.Y = 17.58
obj.Width = 67.87
obj.Height = 2.88
obj.Content = "For the year Jan. 1–Dec. 31, 2025, or other tax year beginning "

Set obj = layout.CreateObject(1, "Text_10")
obj.X = 112.26
obj.Y = 17.58
obj.Width = 16.42
obj.Height = 2.88
obj.Content = ", 2025, ending "

Set obj = layout.CreateObject(1, "Text_11")
obj.X = 160.69
obj.Y = 17.58
obj.Width = 4.80
obj.Height = 2.88
obj.Content = ", 20 "

Set obj = layout.CreateObject(1, "Text_12")
obj.X = 174.09
obj.Y = 17.58
obj.Width = 28.72
obj.Height = 2.88
obj.Content = "See separate instructions."

Set obj = layout.CreateObject(1, "Text_13")
obj.X = 16.37
obj.Y = 21.95
obj.Width = 36.94
obj.Height = 2.88
obj.Content = "Filed pursuant to section 301.9100-2"

Set obj = layout.CreateObject(1, "Text_14")
obj.X = 58.41
obj.Y = 21.95
obj.Width = 14.86
obj.Height = 2.88
obj.Content = "Combat zone"

Set obj = layout.CreateObject(1, "Text_15")
obj.X = 135.86
obj.Y = 21.95
obj.Width = 10.84
obj.Height = 2.88
obj.Content = "Deceased"

Set obj = layout.CreateObject(1, "Text_16")
obj.X = 146.70
obj.Y = 21.95
obj.Width = 0.94
obj.Height = 2.91
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_17")
obj.X = 147.64
obj.Y = 21.99
obj.Width = 7.73
obj.Height = 2.88
obj.Content = "MM     "

Set obj = layout.CreateObject(1, "Text_18")
obj.X = 155.37
obj.Y = 21.99
obj.Width = 0.34
obj.Height = 2.88
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_19")
obj.X = 155.72
obj.Y = 21.99
obj.Width = 6.91
obj.Height = 2.88
obj.Content = "DD     "

Set obj = layout.CreateObject(1, "Text_20")
obj.X = 162.62
obj.Y = 21.99
obj.Width = 0.34
obj.Height = 2.88
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_21")
obj.X = 162.97
obj.Y = 21.99
obj.Width = 6.40
obj.Height = 2.88
obj.Content = "YYYY"

Set obj = layout.CreateObject(1, "Text_22")
obj.X = 153.07
obj.Y = 21.99
obj.Width = 0.82
obj.Height = 2.88
obj.Content = "/"

Set obj = layout.CreateObject(1, "Text_23")
obj.X = 160.69
obj.Y = 21.99
obj.Width = 0.82
obj.Height = 2.88
obj.Content = "/"

Set obj = layout.CreateObject(1, "Text_24")
obj.X = 171.38
obj.Y = 21.99
obj.Width = 8.41
obj.Height = 2.88
obj.Content = "Spouse"

Set obj = layout.CreateObject(1, "Text_25")
obj.X = 179.79
obj.Y = 21.99
obj.Width = 0.86
obj.Height = 2.88
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_26")
obj.X = 180.65
obj.Y = 21.99
obj.Width = 7.73
obj.Height = 2.88
obj.Content = "MM     "

Set obj = layout.CreateObject(1, "Text_27")
obj.X = 188.39
obj.Y = 21.99
obj.Width = 0.34
obj.Height = 2.88
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_28")
obj.X = 188.73
obj.Y = 21.99
obj.Width = 6.91
obj.Height = 2.88
obj.Content = "DD     "

Set obj = layout.CreateObject(1, "Text_29")
obj.X = 195.64
obj.Y = 21.99
obj.Width = 0.34
obj.Height = 2.88
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_30")
obj.X = 195.98
obj.Y = 21.99
obj.Width = 6.40
obj.Height = 2.88
obj.Content = "YYYY"

Set obj = layout.CreateObject(1, "Text_31")
obj.X = 186.08
obj.Y = 21.99
obj.Width = 0.82
obj.Height = 2.88
obj.Content = "/"

Set obj = layout.CreateObject(1, "Text_32")
obj.X = 193.70
obj.Y = 21.99
obj.Width = 0.82
obj.Height = 2.88
obj.Content = "/"

Set obj = layout.CreateObject(1, "Text_33")
obj.X = 16.37
obj.Y = 26.18
obj.Width = 6.17
obj.Height = 2.88
obj.Content = "Other"

Set obj = layout.CreateObject(1, "Text_34")
obj.X = 12.70
obj.Y = 30.10
obj.Width = 36.86
obj.Height = 2.88
obj.Content = "Your first name and middle initial "

Set obj = layout.CreateObject(1, "Text_35")
obj.X = 90.29
obj.Y = 30.10
obj.Width = 12.21
obj.Height = 2.88
obj.Content = "Last name "

Set obj = layout.CreateObject(1, "Text_36")
obj.X = 166.47
obj.Y = 30.04
obj.Width = 33.69
obj.Height = 2.95
obj.Content = "Your social security number "

Set obj = layout.CreateObject(1, "Text_37")
obj.X = 12.70
obj.Y = 38.56
obj.Width = 56.20
obj.Height = 2.88
obj.Content = "If joint return, spouse’s first name and middle initial"

Set obj = layout.CreateObject(1, "Text_38")
obj.X = 90.29
obj.Y = 38.56
obj.Width = 12.21
obj.Height = 2.88
obj.Content = "Last name "

Set obj = layout.CreateObject(1, "Text_39")
obj.X = 166.47
obj.Y = 38.51
obj.Width = 37.21
obj.Height = 2.95
obj.Content = "Spouse’s social security number "

Set obj = layout.CreateObject(1, "Text_40")
obj.X = 12.70
obj.Y = 47.03
obj.Width = 84.33
obj.Height = 2.88
obj.Content = "Home address (number and street). If you have a P.O. box, see instructions. "

Set obj = layout.CreateObject(1, "Text_41")
obj.X = 148.70
obj.Y = 47.03
obj.Width = 9.38
obj.Height = 2.88
obj.Content = "Apt. no. "

Set obj = layout.CreateObject(1, "Text_42")
obj.X = 12.70
obj.Y = 55.49
obj.Width = 94.56
obj.Height = 2.88
obj.Content = "City, town, or post office. If you have a foreign address, also complete spaces below. "

Set obj = layout.CreateObject(1, "Text_43")
obj.X = 118.23
obj.Y = 55.49
obj.Width = 5.81
obj.Height = 2.88
obj.Content = "State"

Set obj = layout.CreateObject(1, "Text_44")
obj.X = 141.08
obj.Y = 55.49
obj.Width = 9.97
obj.Height = 2.88
obj.Content = "ZIP code"

Set obj = layout.CreateObject(1, "Text_45")
obj.X = 12.70
obj.Y = 63.96
obj.Width = 51.60
obj.Height = 2.88
obj.Content = "Foreign country name                                        "

Set obj = layout.CreateObject(1, "Text_46")
obj.X = 80.13
obj.Y = 63.96
obj.Width = 85.00
obj.Height = 2.88
obj.Content = "Foreign province/state/county                                       Foreign postal code   "

Set obj = layout.CreateObject(1, "Text_47")
obj.X = 165.77
obj.Y = 46.69
obj.Width = 37.18
obj.Height = 2.82
obj.Content = "Check here if your main home, and your "

Set obj = layout.CreateObject(1, "Text_48")
obj.X = 165.77
obj.Y = 49.33
obj.Width = 34.81
obj.Height = 2.82
obj.Content = "spouse’s if filing a joint return, was in "

Set obj = layout.CreateObject(1, "Text_49")
obj.X = 165.77
obj.Y = 51.98
obj.Width = 32.96
obj.Height = 2.82
obj.Content = "the U.S. for more than half of 2025. "

Set obj = layout.CreateObject(1, "Text_50")
obj.X = 166.67
obj.Y = 55.06
obj.Width = 34.87
obj.Height = 3.34
obj.Content = "Presidential Election Campaign"

Set obj = layout.CreateObject(1, "Text_51")
obj.X = 165.77
obj.Y = 58.10
obj.Width = 37.78
obj.Height = 2.88
obj.Content = "Check here if you, or your spouse "

Set obj = layout.CreateObject(1, "Text_52")
obj.X = 165.77
obj.Y = 60.57
obj.Width = 34.30
obj.Height = 2.88
obj.Content = "if filing jointly, want $3 to go to "

Set obj = layout.CreateObject(1, "Text_53")
obj.X = 165.77
obj.Y = 63.04
obj.Width = 36.14
obj.Height = 2.88
obj.Content = "this fund. Checking a box below "

Set obj = layout.CreateObject(1, "Text_54")
obj.X = 165.77
obj.Y = 65.51
obj.Width = 37.50
obj.Height = 2.88
obj.Content = "will not change your tax or refund."

Set obj = layout.CreateObject(1, "Text_55")
obj.X = 173.95
obj.Y = 68.48
obj.Width = 5.31
obj.Height = 2.95
obj.Content = "You "

Set obj = layout.CreateObject(1, "Text_56")
obj.X = 189.19
obj.Y = 68.48
obj.Width = 9.51
obj.Height = 2.95
obj.Content = "Spouse "

Set obj = layout.CreateObject(1, "Text_57")
obj.X = 12.70
obj.Y = 72.54
obj.Width = 17.49
obj.Height = 4.18
obj.Content = "Filing Status"

Set obj = layout.CreateObject(1, "Text_58")
obj.X = 12.70
obj.Y = 78.42
obj.Width = 13.72
obj.Height = 2.88
obj.Content = "Check only  "

Set obj = layout.CreateObject(1, "Text_59")
obj.X = 12.70
obj.Y = 81.15
obj.Width = 10.33
obj.Height = 2.88
obj.Content = "one box. "

Set obj = layout.CreateObject(1, "Text_60")
obj.X = 38.80
obj.Y = 72.69
obj.Width = 8.57
obj.Height = 3.29
obj.Content = "Single "

Set obj = layout.CreateObject(1, "Text_61")
obj.X = 38.80
obj.Y = 76.92
obj.Width = 62.87
obj.Height = 3.29
obj.Content = "Married filing jointly (even if only one had income) "

Set obj = layout.CreateObject(1, "Text_62")
obj.X = 38.80
obj.Y = 81.15
obj.Width = 74.46
obj.Height = 3.29
obj.Content = "Married filing separately (MFS). Enter spouse’s SSN above "

Set obj = layout.CreateObject(1, "Text_63")
obj.X = 38.80
obj.Y = 85.03
obj.Width = 24.10
obj.Height = 3.29
obj.Content = "and full name here:"

Set obj = layout.CreateObject(1, "Text_64")
obj.X = 127.68
obj.Y = 72.69
obj.Width = 32.40
obj.Height = 3.29
obj.Content = "Head of household (HOH)"

Set obj = layout.CreateObject(1, "Text_65")
obj.X = 127.68
obj.Y = 76.92
obj.Width = 42.54
obj.Height = 3.29
obj.Content = "Qualifying surviving spouse (QSS)"

Set obj = layout.CreateObject(1, "Text_66")
obj.X = 127.68
obj.Y = 80.48
obj.Width = 76.05
obj.Height = 3.29
obj.Content = "If you checked the HOH or QSS box, enter the child’s name "

Set obj = layout.CreateObject(1, "Text_67")
obj.X = 127.68
obj.Y = 83.48
obj.Width = 71.76
obj.Height = 3.29
obj.Content = "if the qualifying person is a child but not your dependent:"

Set obj = layout.CreateObject(1, "Text_68")
obj.X = 38.80
obj.Y = 90.94
obj.Width = 161.49
obj.Height = 3.29
obj.Content = "If treating a nonresident alien or dual-status alien spouse as a U.S. resident for the entire tax year, check the box and enter their "

Set obj = layout.CreateObject(1, "Text_69")
obj.X = 38.80
obj.Y = 94.56
obj.Width = 70.19
obj.Height = 3.29
obj.Content = "name (see instructions and attach statement if required):"

Set obj = layout.CreateObject(1, "Text_70")
obj.X = 12.70
obj.Y = 98.94
obj.Width = 19.25
obj.Height = 4.18
obj.Content = "Digital Assets"

Set obj = layout.CreateObject(1, "Text_71")
obj.X = 34.42
obj.Y = 98.37
obj.Width = 145.19
obj.Height = 3.29
obj.Content = "At any time during 2025, did you: (a) receive (as a reward, award, or payment for property or services); or (b) sell, "

Set obj = layout.CreateObject(1, "Text_72")
obj.X = 34.43
obj.Y = 101.19
obj.Width = 136.80
obj.Height = 3.29
obj.Content = "exchange, or otherwise dispose of a digital asset (or a financial interest in a digital asset)? (See instructions.) "

Set obj = layout.CreateObject(1, "Text_73")
obj.X = 173.53
obj.Y = 101.19
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_74")
obj.X = 177.77
obj.Y = 101.19
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_75")
obj.X = 186.65
obj.Y = 101.02
obj.Width = 5.80
obj.Height = 3.37
obj.Content = "Yes "

Set obj = layout.CreateObject(1, "Text_76")
obj.X = 199.35
obj.Y = 101.02
obj.Width = 3.81
obj.Height = 3.37
obj.Content = "No"

Set obj = layout.CreateObject(1, "Text_77")
obj.X = 12.70
obj.Y = 105.29
obj.Width = 16.59
obj.Height = 4.18
obj.Content = "Dependents"

Set obj = layout.CreateObject(1, "Text_78")
obj.X = 12.70
obj.Y = 110.20
obj.Width = 18.66
obj.Height = 2.88
obj.Content = "(see instructions)"

Set obj = layout.CreateObject(1, "Text_79")
obj.X = 12.70
obj.Y = 115.76
obj.Width = 9.02
obj.Height = 3.08
obj.Content = "If more "

Set obj = layout.CreateObject(1, "Text_80")
obj.X = 12.70
obj.Y = 118.67
obj.Width = 11.32
obj.Height = 3.08
obj.Content = "than four "

Set obj = layout.CreateObject(1, "Text_81")
obj.X = 12.70
obj.Y = 121.58
obj.Width = 15.54
obj.Height = 3.08
obj.Content = "dependents, "

Set obj = layout.CreateObject(1, "Text_82")
obj.X = 12.70
obj.Y = 124.49
obj.Width = 19.04
obj.Height = 3.08
obj.Content = "see instructions "

Set obj = layout.CreateObject(1, "Text_83")
obj.X = 12.70
obj.Y = 127.40
obj.Width = 13.04
obj.Height = 3.08
obj.Content = "and check "

Set obj = layout.CreateObject(1, "Text_84")
obj.X = 12.70
obj.Y = 130.31
obj.Width = 5.93
obj.Height = 3.08
obj.Content = "here "

Set obj = layout.CreateObject(1, "Text_85")
obj.X = 21.16
obj.Y = 130.31
obj.Width = 0.74
obj.Height = 3.08
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_86")
obj.X = 25.39
obj.Y = 130.31
obj.Width = 0.74
obj.Height = 3.08
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_87")
obj.X = 62.36
obj.Y = 105.34
obj.Width = 14.95
obj.Height = 2.95
obj.Content = "Dependent 1"

Set obj = layout.CreateObject(1, "Text_88")
obj.X = 100.45
obj.Y = 105.34
obj.Width = 14.95
obj.Height = 2.95
obj.Content = "Dependent 2"

Set obj = layout.CreateObject(1, "Text_89")
obj.X = 138.54
obj.Y = 105.34
obj.Width = 14.95
obj.Height = 2.95
obj.Content = "Dependent 3"

Set obj = layout.CreateObject(1, "Text_90")
obj.X = 176.63
obj.Y = 105.34
obj.Width = 14.95
obj.Height = 2.95
obj.Content = "Dependent 4"

Set obj = layout.CreateObject(1, "Text_91")
obj.X = 33.01
obj.Y = 109.44
obj.Width = 3.52
obj.Height = 2.95
obj.Content = "(1) "

Set obj = layout.CreateObject(1, "Text_92")
obj.X = 36.53
obj.Y = 109.50
obj.Width = 11.62
obj.Height = 2.88
obj.Content = "First name"

Set obj = layout.CreateObject(1, "Text_93")
obj.X = 33.01
obj.Y = 113.67
obj.Width = 2.83
obj.Height = 2.95
obj.Content = "(2)"

Set obj = layout.CreateObject(1, "Text_94")
obj.X = 35.85
obj.Y = 113.73
obj.Width = 12.21
obj.Height = 2.88
obj.Content = " Last name"

Set obj = layout.CreateObject(1, "Text_95")
obj.X = 33.01
obj.Y = 117.90
obj.Width = 3.52
obj.Height = 2.95
obj.Content = "(3) "

Set obj = layout.CreateObject(1, "Text_96")
obj.X = 36.53
obj.Y = 117.96
obj.Width = 4.98
obj.Height = 2.88
obj.Content = "SSN"

Set obj = layout.CreateObject(1, "Text_97")
obj.X = 33.01
obj.Y = 122.14
obj.Width = 3.52
obj.Height = 2.95
obj.Content = "(4) "

Set obj = layout.CreateObject(1, "Text_98")
obj.X = 36.53
obj.Y = 122.19
obj.Width = 13.49
obj.Height = 2.88
obj.Content = "Relationship"

Set obj = layout.CreateObject(1, "Text_99")
obj.X = 33.01
obj.Y = 126.03
obj.Width = 2.83
obj.Height = 2.95
obj.Content = "(5)"

Set obj = layout.CreateObject(1, "Text_100")
obj.X = 35.85
obj.Y = 126.08
obj.Width = 0.69
obj.Height = 2.88
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_101")
obj.X = 36.53
obj.Y = 126.08
obj.Width = 13.66
obj.Height = 2.88
obj.Content = "Check if lived"

Set obj = layout.CreateObject(1, "Text_102")
obj.X = 50.19
obj.Y = 126.08
obj.Width = 0.69
obj.Height = 2.88
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_103")
obj.X = 33.01
obj.Y = 128.64
obj.Width = 16.32
obj.Height = 2.88
obj.Content = "with you more "

Set obj = layout.CreateObject(1, "Text_104")
obj.X = 33.01
obj.Y = 131.20
obj.Width = 17.21
obj.Height = 2.88
obj.Content = "than half of 2025"

Set obj = layout.CreateObject(1, "Text_105")
obj.X = 54.82
obj.Y = 126.68
obj.Width = 2.88
obj.Height = 2.95
obj.Content = "(a)"

Set obj = layout.CreateObject(1, "Text_106")
obj.X = 63.84
obj.Y = 126.74
obj.Width = 4.16
obj.Height = 2.88
obj.Content = "Yes"

Set obj = layout.CreateObject(1, "Text_107")
obj.X = 54.73
obj.Y = 130.91
obj.Width = 2.97
obj.Height = 2.95
obj.Content = "(b)"

Set obj = layout.CreateObject(1, "Text_108")
obj.X = 63.84
obj.Y = 130.97
obj.Width = 16.65
obj.Height = 2.88
obj.Content = "And in the U.S."

Set obj = layout.CreateObject(1, "Text_109")
obj.X = 92.91
obj.Y = 126.68
obj.Width = 2.88
obj.Height = 2.95
obj.Content = "(a)"

Set obj = layout.CreateObject(1, "Text_110")
obj.X = 101.93
obj.Y = 126.74
obj.Width = 4.16
obj.Height = 2.88
obj.Content = "Yes"

Set obj = layout.CreateObject(1, "Text_111")
obj.X = 92.82
obj.Y = 130.91
obj.Width = 2.97
obj.Height = 2.95
obj.Content = "(b)"

Set obj = layout.CreateObject(1, "Text_112")
obj.X = 101.93
obj.Y = 130.97
obj.Width = 16.65
obj.Height = 2.88
obj.Content = "And in the U.S."

Set obj = layout.CreateObject(1, "Text_113")
obj.X = 131.01
obj.Y = 126.68
obj.Width = 2.88
obj.Height = 2.95
obj.Content = "(a)"

Set obj = layout.CreateObject(1, "Text_114")
obj.X = 140.02
obj.Y = 126.74
obj.Width = 4.16
obj.Height = 2.88
obj.Content = "Yes"

Set obj = layout.CreateObject(1, "Text_115")
obj.X = 130.91
obj.Y = 130.91
obj.Width = 2.97
obj.Height = 2.95
obj.Content = "(b)"

Set obj = layout.CreateObject(1, "Text_116")
obj.X = 140.02
obj.Y = 130.97
obj.Width = 16.65
obj.Height = 2.88
obj.Content = "And in the U.S."

Set obj = layout.CreateObject(1, "Text_117")
obj.X = 169.10
obj.Y = 126.68
obj.Width = 2.88
obj.Height = 2.95
obj.Content = "(a)"

Set obj = layout.CreateObject(1, "Text_118")
obj.X = 178.11
obj.Y = 126.74
obj.Width = 4.16
obj.Height = 2.88
obj.Content = "Yes"

Set obj = layout.CreateObject(1, "Text_119")
obj.X = 169.01
obj.Y = 130.91
obj.Width = 2.97
obj.Height = 2.95
obj.Content = "(b)"

Set obj = layout.CreateObject(1, "Text_120")
obj.X = 178.11
obj.Y = 130.97
obj.Width = 16.65
obj.Height = 2.88
obj.Content = "And in the U.S."

Set obj = layout.CreateObject(1, "Text_121")
obj.X = 33.01
obj.Y = 134.83
obj.Width = 2.83
obj.Height = 2.95
obj.Content = "(6)"

Set obj = layout.CreateObject(1, "Text_122")
obj.X = 35.85
obj.Y = 134.89
obj.Width = 9.74
obj.Height = 2.88
obj.Content = " Check if"

Set obj = layout.CreateObject(1, "Text_123")
obj.X = 56.29
obj.Y = 134.50
obj.Width = 10.29
obj.Height = 2.88
obj.Content = "Full-time "

Set obj = layout.CreateObject(1, "Text_124")
obj.X = 56.29
obj.Y = 136.61
obj.Width = 8.33
obj.Height = 2.88
obj.Content = "student"

Set obj = layout.CreateObject(1, "Text_125")
obj.X = 74.07
obj.Y = 134.50
obj.Width = 14.50
obj.Height = 2.88
obj.Content = "Permanently "

Set obj = layout.CreateObject(1, "Text_126")
obj.X = 74.07
obj.Y = 136.61
obj.Width = 12.16
obj.Height = 2.88
obj.Content = "and totally "

Set obj = layout.CreateObject(1, "Text_127")
obj.X = 74.07
obj.Y = 138.73
obj.Width = 9.37
obj.Height = 2.88
obj.Content = "disabled"

Set obj = layout.CreateObject(1, "Text_128")
obj.X = 94.38
obj.Y = 134.50
obj.Width = 10.29
obj.Height = 2.88
obj.Content = "Full-time "

Set obj = layout.CreateObject(1, "Text_129")
obj.X = 94.38
obj.Y = 136.61
obj.Width = 8.33
obj.Height = 2.88
obj.Content = "student"

Set obj = layout.CreateObject(1, "Text_130")
obj.X = 112.16
obj.Y = 134.50
obj.Width = 14.50
obj.Height = 2.88
obj.Content = "Permanently "

Set obj = layout.CreateObject(1, "Text_131")
obj.X = 112.16
obj.Y = 136.61
obj.Width = 12.16
obj.Height = 2.88
obj.Content = "and totally "

Set obj = layout.CreateObject(1, "Text_132")
obj.X = 112.16
obj.Y = 138.73
obj.Width = 9.37
obj.Height = 2.88
obj.Content = "disabled"

Set obj = layout.CreateObject(1, "Text_133")
obj.X = 132.47
obj.Y = 134.50
obj.Width = 10.29
obj.Height = 2.88
obj.Content = "Full-time "

Set obj = layout.CreateObject(1, "Text_134")
obj.X = 132.47
obj.Y = 136.61
obj.Width = 8.33
obj.Height = 2.88
obj.Content = "student"

Set obj = layout.CreateObject(1, "Text_135")
obj.X = 150.25
obj.Y = 134.50
obj.Width = 14.50
obj.Height = 2.88
obj.Content = "Permanently "

Set obj = layout.CreateObject(1, "Text_136")
obj.X = 150.25
obj.Y = 136.61
obj.Width = 12.16
obj.Height = 2.88
obj.Content = "and totally "

Set obj = layout.CreateObject(1, "Text_137")
obj.X = 150.25
obj.Y = 138.73
obj.Width = 9.37
obj.Height = 2.88
obj.Content = "disabled"

Set obj = layout.CreateObject(1, "Text_138")
obj.X = 170.57
obj.Y = 134.50
obj.Width = 10.29
obj.Height = 2.88
obj.Content = "Full-time "

Set obj = layout.CreateObject(1, "Text_139")
obj.X = 170.57
obj.Y = 136.61
obj.Width = 8.33
obj.Height = 2.88
obj.Content = "student"

Set obj = layout.CreateObject(1, "Text_140")
obj.X = 188.34
obj.Y = 134.50
obj.Width = 14.50
obj.Height = 2.88
obj.Content = "Permanently "

Set obj = layout.CreateObject(1, "Text_141")
obj.X = 188.34
obj.Y = 136.61
obj.Width = 12.16
obj.Height = 2.88
obj.Content = "and totally "

Set obj = layout.CreateObject(1, "Text_142")
obj.X = 188.34
obj.Y = 138.73
obj.Width = 9.37
obj.Height = 2.88
obj.Content = "disabled"

Set obj = layout.CreateObject(1, "Text_143")
obj.X = 33.01
obj.Y = 142.24
obj.Width = 2.83
obj.Height = 2.95
obj.Content = "(7)"

Set obj = layout.CreateObject(1, "Text_144")
obj.X = 35.85
obj.Y = 142.30
obj.Width = 8.64
obj.Height = 2.88
obj.Content = " Credits"

Set obj = layout.CreateObject(1, "Text_145")
obj.X = 56.29
obj.Y = 141.90
obj.Width = 10.47
obj.Height = 2.88
obj.Content = "Child tax "

Set obj = layout.CreateObject(1, "Text_146")
obj.X = 56.29
obj.Y = 144.02
obj.Width = 6.26
obj.Height = 2.88
obj.Content = "credit"

Set obj = layout.CreateObject(1, "Text_147")
obj.X = 74.07
obj.Y = 141.90
obj.Width = 11.06
obj.Height = 2.88
obj.Content = "Credit for "

Set obj = layout.CreateObject(1, "Text_148")
obj.X = 74.07
obj.Y = 144.02
obj.Width = 6.40
obj.Height = 2.88
obj.Content = "other "

Set obj = layout.CreateObject(1, "Text_149")
obj.X = 74.07
obj.Y = 146.13
obj.Width = 13.13
obj.Height = 2.88
obj.Content = "dependents"

Set obj = layout.CreateObject(1, "Text_150")
obj.X = 94.38
obj.Y = 141.90
obj.Width = 10.47
obj.Height = 2.88
obj.Content = "Child tax "

Set obj = layout.CreateObject(1, "Text_151")
obj.X = 94.38
obj.Y = 144.02
obj.Width = 6.26
obj.Height = 2.88
obj.Content = "credit"

Set obj = layout.CreateObject(1, "Text_152")
obj.X = 112.16
obj.Y = 141.90
obj.Width = 11.06
obj.Height = 2.88
obj.Content = "Credit for "

Set obj = layout.CreateObject(1, "Text_153")
obj.X = 112.16
obj.Y = 144.02
obj.Width = 6.40
obj.Height = 2.88
obj.Content = "other "

Set obj = layout.CreateObject(1, "Text_154")
obj.X = 112.16
obj.Y = 146.13
obj.Width = 13.13
obj.Height = 2.88
obj.Content = "dependents"

Set obj = layout.CreateObject(1, "Text_155")
obj.X = 132.47
obj.Y = 141.90
obj.Width = 10.47
obj.Height = 2.88
obj.Content = "Child tax "

Set obj = layout.CreateObject(1, "Text_156")
obj.X = 132.47
obj.Y = 144.02
obj.Width = 6.26
obj.Height = 2.88
obj.Content = "credit"

Set obj = layout.CreateObject(1, "Text_157")
obj.X = 150.25
obj.Y = 141.90
obj.Width = 11.06
obj.Height = 2.88
obj.Content = "Credit for "

Set obj = layout.CreateObject(1, "Text_158")
obj.X = 150.25
obj.Y = 144.02
obj.Width = 6.40
obj.Height = 2.88
obj.Content = "other "

Set obj = layout.CreateObject(1, "Text_159")
obj.X = 150.25
obj.Y = 146.13
obj.Width = 13.13
obj.Height = 2.88
obj.Content = "dependents"

Set obj = layout.CreateObject(1, "Text_160")
obj.X = 170.57
obj.Y = 141.90
obj.Width = 10.47
obj.Height = 2.88
obj.Content = "Child tax "

Set obj = layout.CreateObject(1, "Text_161")
obj.X = 170.57
obj.Y = 144.02
obj.Width = 6.26
obj.Height = 2.88
obj.Content = "credit"

Set obj = layout.CreateObject(1, "Text_162")
obj.X = 188.34
obj.Y = 141.90
obj.Width = 11.06
obj.Height = 2.88
obj.Content = "Credit for "

Set obj = layout.CreateObject(1, "Text_163")
obj.X = 188.34
obj.Y = 144.02
obj.Width = 6.40
obj.Height = 2.88
obj.Content = "other "

Set obj = layout.CreateObject(1, "Text_164")
obj.X = 188.34
obj.Y = 146.13
obj.Width = 13.13
obj.Height = 2.88
obj.Content = "dependents"

Set obj = layout.CreateObject(1, "Text_165")
obj.X = 38.09
obj.Y = 149.38
obj.Width = 160.29
obj.Height = 3.29
obj.Content = "Check if your filing status is MFS or HOH and you lived apart from your spouse for the last 6 months of 2025, or you are legally "

Set obj = layout.CreateObject(1, "Text_166")
obj.X = 38.09
obj.Y = 152.28
obj.Width = 164.15
obj.Height = 3.29
obj.Content = "separated according to your state law under a written separation agreement or a decree of separate maintenance and you did not "

Set obj = layout.CreateObject(1, "Text_167")
obj.X = 38.09
obj.Y = 155.19
obj.Width = 78.87
obj.Height = 3.29
obj.Content = "live in the same household as your spouse at the end of 2025. "

Set obj = layout.CreateObject(1, "Text_168")
obj.X = 12.70
obj.Y = 159.17
obj.Width = 12.27
obj.Height = 4.60
obj.Content = "Income "

Set obj = layout.CreateObject(1, "Text_169")
obj.X = 12.70
obj.Y = 165.12
obj.Width = 18.06
obj.Height = 2.95
obj.Content = "Attach Form(s) "

Set obj = layout.CreateObject(1, "Text_170")
obj.X = 12.70
obj.Y = 167.86
obj.Width = 17.87
obj.Height = 2.95
obj.Content = "W-2 here. Also "

Set obj = layout.CreateObject(1, "Text_171")
obj.X = 12.70
obj.Y = 170.59
obj.Width = 16.32
obj.Height = 2.95
obj.Content = "attach Forms "

Set obj = layout.CreateObject(1, "Text_172")
obj.X = 12.70
obj.Y = 173.32
obj.Width = 12.34
obj.Height = 2.95
obj.Content = "W-2G and "

Set obj = layout.CreateObject(1, "Text_173")
obj.X = 12.70
obj.Y = 176.06
obj.Width = 15.41
obj.Height = 2.95
obj.Content = "1099-R if tax "

Set obj = layout.CreateObject(1, "Text_174")
obj.X = 12.70
obj.Y = 178.79
obj.Width = 16.13
obj.Height = 2.95
obj.Content = "was withheld."

Set obj = layout.CreateObject(1, "Text_175")
obj.X = 28.83
obj.Y = 178.85
obj.Width = 1.37
obj.Height = 2.88
obj.Content = "  "

Set obj = layout.CreateObject(1, "Text_176")
obj.X = 12.70
obj.Y = 182.29
obj.Width = 15.18
obj.Height = 2.88
obj.Content = "If you did not "

Set obj = layout.CreateObject(1, "Text_177")
obj.X = 12.70
obj.Y = 185.02
obj.Width = 12.67
obj.Height = 2.88
obj.Content = "get a Form "

Set obj = layout.CreateObject(1, "Text_178")
obj.X = 12.70
obj.Y = 187.75
obj.Width = 10.56
obj.Height = 2.88
obj.Content = "W-2, see "

Set obj = layout.CreateObject(1, "Text_179")
obj.X = 12.70
obj.Y = 190.49
obj.Width = 13.49
obj.Height = 2.88
obj.Content = "instructions."

Set obj = layout.CreateObject(1, "Text_180")
obj.X = 33.98
obj.Y = 159.39
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "1 a"

Set obj = layout.CreateObject(1, "Text_181")
obj.X = 40.63
obj.Y = 159.45
obj.Width = 71.08
obj.Height = 3.29
obj.Content = "Total amount from Form(s) W-2, box 1 (see instructions) "

Set obj = layout.CreateObject(1, "Text_182")
obj.X = 114.27
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_183")
obj.X = 118.51
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_184")
obj.X = 122.74
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_185")
obj.X = 126.97
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_186")
obj.X = 131.20
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_187")
obj.X = 135.44
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_188")
obj.X = 139.67
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_189")
obj.X = 143.90
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_190")
obj.X = 148.13
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_191")
obj.X = 152.37
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_192")
obj.X = 156.60
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_193")
obj.X = 160.83
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_194")
obj.X = 165.06
obj.Y = 159.45
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_195")
obj.X = 172.36
obj.Y = 159.39
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "1a"

Set obj = layout.CreateObject(1, "Text_196")
obj.X = 35.55
obj.Y = 163.62
obj.Width = 1.72
obj.Height = 3.37
obj.Content = "b"

Set obj = layout.CreateObject(1, "Text_197")
obj.X = 40.63
obj.Y = 163.69
obj.Width = 74.43
obj.Height = 3.29
obj.Content = "Household employee wages not reported on Form(s) W-2 ."

Set obj = layout.CreateObject(1, "Text_198")
obj.X = 118.51
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_199")
obj.X = 122.74
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_200")
obj.X = 126.97
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_201")
obj.X = 131.20
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_202")
obj.X = 135.44
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_203")
obj.X = 139.67
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_204")
obj.X = 143.90
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_205")
obj.X = 148.13
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_206")
obj.X = 152.37
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_207")
obj.X = 156.60
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_208")
obj.X = 160.83
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_209")
obj.X = 165.06
obj.Y = 163.69
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_210")
obj.X = 172.31
obj.Y = 163.62
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "1b"

Set obj = layout.CreateObject(1, "Text_211")
obj.X = 35.55
obj.Y = 167.85
obj.Width = 1.62
obj.Height = 3.37
obj.Content = "c"

Set obj = layout.CreateObject(1, "Text_212")
obj.X = 40.63
obj.Y = 167.92
obj.Width = 65.43
obj.Height = 3.29
obj.Content = "Tip income not reported on line 1a (see instructions)"

Set obj = layout.CreateObject(1, "Text_213")
obj.X = 110.04
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_214")
obj.X = 114.27
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_215")
obj.X = 118.51
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_216")
obj.X = 122.74
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_217")
obj.X = 126.97
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_218")
obj.X = 131.20
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_219")
obj.X = 135.44
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_220")
obj.X = 139.67
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_221")
obj.X = 143.90
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_222")
obj.X = 148.13
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_223")
obj.X = 152.37
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_224")
obj.X = 156.60
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_225")
obj.X = 160.83
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_226")
obj.X = 165.06
obj.Y = 167.92
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_227")
obj.X = 172.36
obj.Y = 167.85
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "1c"

Set obj = layout.CreateObject(1, "Text_228")
obj.X = 35.55
obj.Y = 172.09
obj.Width = 1.72
obj.Height = 3.37
obj.Content = "d"

Set obj = layout.CreateObject(1, "Text_229")
obj.X = 40.63
obj.Y = 172.15
obj.Width = 95.59
obj.Height = 3.29
obj.Content = "Medicaid waiver payments not reported on Form(s) W-2 (see instructions)  ."

Set obj = layout.CreateObject(1, "Text_230")
obj.X = 139.67
obj.Y = 172.15
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_231")
obj.X = 143.90
obj.Y = 172.15
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_232")
obj.X = 148.13
obj.Y = 172.15
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_233")
obj.X = 152.37
obj.Y = 172.15
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_234")
obj.X = 156.60
obj.Y = 172.15
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_235")
obj.X = 160.83
obj.Y = 172.15
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_236")
obj.X = 165.06
obj.Y = 172.15
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_237")
obj.X = 172.31
obj.Y = 172.09
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "1d"

Set obj = layout.CreateObject(1, "Text_238")
obj.X = 35.55
obj.Y = 176.32
obj.Width = 1.62
obj.Height = 3.37
obj.Content = "e"

Set obj = layout.CreateObject(1, "Text_239")
obj.X = 40.63
obj.Y = 176.38
obj.Width = 73.80
obj.Height = 3.29
obj.Content = "Taxable dependent care benefits from Form 2441, line 26  "

Set obj = layout.CreateObject(1, "Text_240")
obj.X = 118.51
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_241")
obj.X = 122.74
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_242")
obj.X = 126.97
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_243")
obj.X = 131.20
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_244")
obj.X = 135.44
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_245")
obj.X = 139.67
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_246")
obj.X = 143.90
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_247")
obj.X = 148.13
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_248")
obj.X = 152.37
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_249")
obj.X = 156.60
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_250")
obj.X = 160.83
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_251")
obj.X = 165.06
obj.Y = 176.38
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_252")
obj.X = 172.36
obj.Y = 176.32
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "1e"

Set obj = layout.CreateObject(1, "Text_253")
obj.X = 35.55
obj.Y = 180.55
obj.Width = 0.94
obj.Height = 3.37
obj.Content = "f"

Set obj = layout.CreateObject(1, "Text_254")
obj.X = 40.63
obj.Y = 180.62
obj.Width = 79.34
obj.Height = 3.29
obj.Content = "Employer-provided adoption benefits from Form 8839, line 31  "

Set obj = layout.CreateObject(1, "Text_255")
obj.X = 122.74
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_256")
obj.X = 126.97
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_257")
obj.X = 131.20
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_258")
obj.X = 135.44
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_259")
obj.X = 139.67
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_260")
obj.X = 143.90
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_261")
obj.X = 148.13
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_262")
obj.X = 152.37
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_263")
obj.X = 156.60
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_264")
obj.X = 160.83
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_265")
obj.X = 165.06
obj.Y = 180.62
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_266")
obj.X = 172.70
obj.Y = 180.55
obj.Width = 2.51
obj.Height = 3.37
obj.Content = "1f"

Set obj = layout.CreateObject(1, "Text_267")
obj.X = 35.55
obj.Y = 184.78
obj.Width = 1.72
obj.Height = 3.37
obj.Content = "g"

Set obj = layout.CreateObject(1, "Text_268")
obj.X = 40.63
obj.Y = 184.85
obj.Width = 40.57
obj.Height = 3.29
obj.Content = "Wages from Form 8919, line 6  ."

Set obj = layout.CreateObject(1, "Text_269")
obj.X = 84.65
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_270")
obj.X = 88.88
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_271")
obj.X = 93.11
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_272")
obj.X = 97.35
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_273")
obj.X = 101.58
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_274")
obj.X = 105.81
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_275")
obj.X = 110.04
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_276")
obj.X = 114.27
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_277")
obj.X = 118.51
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_278")
obj.X = 122.74
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_279")
obj.X = 126.97
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_280")
obj.X = 131.20
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_281")
obj.X = 135.44
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_282")
obj.X = 139.67
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_283")
obj.X = 143.90
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_284")
obj.X = 148.13
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_285")
obj.X = 152.37
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_286")
obj.X = 156.60
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_287")
obj.X = 160.83
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_288")
obj.X = 165.06
obj.Y = 184.85
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_289")
obj.X = 172.31
obj.Y = 184.78
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "1g"

Set obj = layout.CreateObject(1, "Text_290")
obj.X = 35.55
obj.Y = 189.02
obj.Width = 1.67
obj.Height = 3.37
obj.Content = "h"

Set obj = layout.CreateObject(1, "Text_291")
obj.X = 40.63
obj.Y = 189.12
obj.Width = 79.87
obj.Height = 3.29
obj.Content = "Other earned income (see instructions). Enter type and amount:"

Set obj = layout.CreateObject(1, "Text_292")
obj.X = 172.33
obj.Y = 189.02
obj.Width = 3.24
obj.Height = 3.37
obj.Content = "1h"

Set obj = layout.CreateObject(1, "Text_293")
obj.X = 35.55
obj.Y = 193.25
obj.Width = 0.73
obj.Height = 3.37
obj.Content = "i"

Set obj = layout.CreateObject(1, "Text_294")
obj.X = 40.63
obj.Y = 193.31
obj.Width = 65.96
obj.Height = 3.29
obj.Content = "Nontaxable combat pay election (see instructions)  ."

Set obj = layout.CreateObject(1, "Text_295")
obj.X = 110.04
obj.Y = 193.31
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_296")
obj.X = 114.27
obj.Y = 193.31
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_297")
obj.X = 118.51
obj.Y = 193.31
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_298")
obj.X = 122.74
obj.Y = 193.31
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_299")
obj.X = 126.97
obj.Y = 193.31
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_300")
obj.X = 131.20
obj.Y = 193.31
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_301")
obj.X = 139.79
obj.Y = 193.25
obj.Width = 2.30
obj.Height = 3.37
obj.Content = "1i"

Set obj = layout.CreateObject(1, "Text_302")
obj.X = 35.55
obj.Y = 197.48
obj.Width = 1.46
obj.Height = 3.37
obj.Content = "z"

Set obj = layout.CreateObject(1, "Text_303")
obj.X = 40.63
obj.Y = 197.55
obj.Width = 31.62
obj.Height = 3.29
obj.Content = "Add lines 1a through 1h  "

Set obj = layout.CreateObject(1, "Text_304")
obj.X = 76.18
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_305")
obj.X = 80.42
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_306")
obj.X = 84.65
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_307")
obj.X = 88.88
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_308")
obj.X = 93.11
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_309")
obj.X = 97.35
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_310")
obj.X = 101.58
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_311")
obj.X = 105.81
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_312")
obj.X = 110.04
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_313")
obj.X = 114.27
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_314")
obj.X = 118.51
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_315")
obj.X = 122.74
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_316")
obj.X = 126.97
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_317")
obj.X = 131.20
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_318")
obj.X = 135.44
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_319")
obj.X = 139.67
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_320")
obj.X = 143.90
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_321")
obj.X = 148.13
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_322")
obj.X = 152.37
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_323")
obj.X = 156.60
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_324")
obj.X = 160.83
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_325")
obj.X = 165.06
obj.Y = 197.55
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_326")
obj.X = 172.44
obj.Y = 197.48
obj.Width = 3.03
obj.Height = 3.37
obj.Content = "1z"

Set obj = layout.CreateObject(1, "Text_327")
obj.X = 12.70
obj.Y = 202.34
obj.Width = 16.60
obj.Height = 2.88
obj.Content = "Attach Sch. B  "

Set obj = layout.CreateObject(1, "Text_328")
obj.X = 12.70
obj.Y = 205.30
obj.Width = 11.80
obj.Height = 2.88
obj.Content = "if required."

Set obj = layout.CreateObject(1, "Text_329")
obj.X = 33.95
obj.Y = 201.71
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "2a"

Set obj = layout.CreateObject(1, "Text_330")
obj.X = 40.63
obj.Y = 201.78
obj.Width = 27.87
obj.Height = 3.29
obj.Content = "Tax-exempt interest ."

Set obj = layout.CreateObject(1, "Text_331")
obj.X = 71.95
obj.Y = 201.78
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_332")
obj.X = 76.18
obj.Y = 201.78
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_333")
obj.X = 83.48
obj.Y = 201.71
obj.Width = 3.97
obj.Height = 3.37
obj.Content = "2a "

Set obj = layout.CreateObject(1, "Text_334")
obj.X = 119.35
obj.Y = 201.71
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "b  "

Set obj = layout.CreateObject(1, "Text_335")
obj.X = 122.65
obj.Y = 201.78
obj.Width = 21.63
obj.Height = 3.29
obj.Content = "Taxable interest  "

Set obj = layout.CreateObject(1, "Text_336")
obj.X = 148.13
obj.Y = 201.78
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_337")
obj.X = 152.37
obj.Y = 201.78
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_338")
obj.X = 156.60
obj.Y = 201.78
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_339")
obj.X = 160.83
obj.Y = 201.78
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_340")
obj.X = 165.06
obj.Y = 201.78
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_341")
obj.X = 172.31
obj.Y = 201.71
obj.Width = 4.08
obj.Height = 3.37
obj.Content = "2b "

Set obj = layout.CreateObject(1, "Text_342")
obj.X = 33.95
obj.Y = 205.95
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "3a"

Set obj = layout.CreateObject(1, "Text_343")
obj.X = 40.63
obj.Y = 206.01
obj.Width = 27.87
obj.Height = 3.29
obj.Content = "Qualified dividends ."

Set obj = layout.CreateObject(1, "Text_344")
obj.X = 71.95
obj.Y = 206.01
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_345")
obj.X = 76.18
obj.Y = 206.01
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_346")
obj.X = 83.48
obj.Y = 205.95
obj.Width = 3.97
obj.Height = 3.37
obj.Content = "3a "

Set obj = layout.CreateObject(1, "Text_347")
obj.X = 119.35
obj.Y = 205.95
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "b  "

Set obj = layout.CreateObject(1, "Text_348")
obj.X = 122.65
obj.Y = 206.01
obj.Width = 26.27
obj.Height = 3.29
obj.Content = "Ordinary dividends ."

Set obj = layout.CreateObject(1, "Text_349")
obj.X = 152.37
obj.Y = 206.01
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_350")
obj.X = 156.60
obj.Y = 206.01
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_351")
obj.X = 160.83
obj.Y = 206.01
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_352")
obj.X = 165.06
obj.Y = 206.01
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_353")
obj.X = 172.31
obj.Y = 205.95
obj.Width = 4.08
obj.Height = 3.37
obj.Content = "3b "

Set obj = layout.CreateObject(1, "Text_354")
obj.X = 35.55
obj.Y = 210.18
obj.Width = 1.62
obj.Height = 3.37
obj.Content = "c"

Set obj = layout.CreateObject(1, "Text_355")
obj.X = 40.63
obj.Y = 210.24
obj.Width = 53.41
obj.Height = 3.29
obj.Content = "Check if your child’s dividends are included in"

Set obj = layout.CreateObject(1, "Text_356")
obj.X = 96.50
obj.Y = 210.18
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "1"

Set obj = layout.CreateObject(1, "Text_357")
obj.X = 104.47
obj.Y = 210.24
obj.Width = 9.93
obj.Height = 3.29
obj.Content = "Line 3a "

Set obj = layout.CreateObject(1, "Text_358")
obj.X = 124.43
obj.Y = 210.18
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "2"

Set obj = layout.CreateObject(1, "Text_359")
obj.X = 132.40
obj.Y = 210.24
obj.Width = 9.31
obj.Height = 3.29
obj.Content = "Line 3b"

Set obj = layout.CreateObject(1, "Text_360")
obj.X = 33.98
obj.Y = 214.41
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "4a"

Set obj = layout.CreateObject(1, "Text_361")
obj.X = 40.63
obj.Y = 214.47
obj.Width = 23.64
obj.Height = 3.29
obj.Content = "IRA distributions ."

Set obj = layout.CreateObject(1, "Text_362")
obj.X = 67.72
obj.Y = 214.47
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_363")
obj.X = 71.95
obj.Y = 214.47
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_364")
obj.X = 76.18
obj.Y = 214.47
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_365")
obj.X = 83.48
obj.Y = 214.41
obj.Width = 3.97
obj.Height = 3.37
obj.Content = "4a "

Set obj = layout.CreateObject(1, "Text_366")
obj.X = 119.35
obj.Y = 214.41
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "b  "

Set obj = layout.CreateObject(1, "Text_367")
obj.X = 122.65
obj.Y = 214.47
obj.Width = 22.04
obj.Height = 3.29
obj.Content = "Taxable amount ."

Set obj = layout.CreateObject(1, "Text_368")
obj.X = 148.13
obj.Y = 214.47
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_369")
obj.X = 152.37
obj.Y = 214.47
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_370")
obj.X = 156.60
obj.Y = 214.47
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_371")
obj.X = 160.83
obj.Y = 214.47
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_372")
obj.X = 165.06
obj.Y = 214.47
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_373")
obj.X = 172.31
obj.Y = 214.41
obj.Width = 4.08
obj.Height = 3.37
obj.Content = "4b "

Set obj = layout.CreateObject(1, "Text_374")
obj.X = 35.55
obj.Y = 218.64
obj.Width = 1.62
obj.Height = 3.37
obj.Content = "c"

Set obj = layout.CreateObject(1, "Text_375")
obj.X = 40.63
obj.Y = 218.71
obj.Width = 33.24
obj.Height = 3.29
obj.Content = "Check if (see instructions) "

Set obj = layout.CreateObject(1, "Text_376")
obj.X = 76.18
obj.Y = 218.71
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_377")
obj.X = 80.42
obj.Y = 218.71
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_378")
obj.X = 84.65
obj.Y = 218.71
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_379")
obj.X = 88.88
obj.Y = 218.71
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_380")
obj.X = 93.11
obj.Y = 218.71
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_381")
obj.X = 96.50
obj.Y = 218.64
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "1"

Set obj = layout.CreateObject(1, "Text_382")
obj.X = 104.47
obj.Y = 218.71
obj.Width = 10.29
obj.Height = 3.29
obj.Content = "Rollover"

Set obj = layout.CreateObject(1, "Text_383")
obj.X = 124.43
obj.Y = 218.64
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "2"

Set obj = layout.CreateObject(1, "Text_384")
obj.X = 132.40
obj.Y = 218.71
obj.Width = 6.17
obj.Height = 3.29
obj.Content = "QCD"

Set obj = layout.CreateObject(1, "Text_385")
obj.X = 147.29
obj.Y = 218.64
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "3"

Set obj = layout.CreateObject(1, "Text_386")
obj.X = 33.98
obj.Y = 222.88
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "5a"

Set obj = layout.CreateObject(1, "Text_387")
obj.X = 40.63
obj.Y = 222.94
obj.Width = 32.10
obj.Height = 3.29
obj.Content = "Pensions and annuities ."

Set obj = layout.CreateObject(1, "Text_388")
obj.X = 76.18
obj.Y = 222.94
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_389")
obj.X = 83.48
obj.Y = 222.88
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "5a"

Set obj = layout.CreateObject(1, "Text_390")
obj.X = 119.35
obj.Y = 222.88
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "b  "

Set obj = layout.CreateObject(1, "Text_391")
obj.X = 122.65
obj.Y = 222.94
obj.Width = 22.04
obj.Height = 3.29
obj.Content = "Taxable amount ."

Set obj = layout.CreateObject(1, "Text_392")
obj.X = 148.13
obj.Y = 222.94
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_393")
obj.X = 152.37
obj.Y = 222.94
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_394")
obj.X = 156.60
obj.Y = 222.94
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_395")
obj.X = 160.83
obj.Y = 222.94
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_396")
obj.X = 165.06
obj.Y = 222.94
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_397")
obj.X = 172.31
obj.Y = 222.88
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "5b"

Set obj = layout.CreateObject(1, "Text_398")
obj.X = 35.55
obj.Y = 227.11
obj.Width = 1.62
obj.Height = 3.37
obj.Content = "c"

Set obj = layout.CreateObject(1, "Text_399")
obj.X = 40.63
obj.Y = 227.17
obj.Width = 33.24
obj.Height = 3.29
obj.Content = "Check if (see instructions) "

Set obj = layout.CreateObject(1, "Text_400")
obj.X = 76.18
obj.Y = 227.17
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_401")
obj.X = 80.42
obj.Y = 227.17
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_402")
obj.X = 84.65
obj.Y = 227.17
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_403")
obj.X = 88.88
obj.Y = 227.17
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_404")
obj.X = 93.11
obj.Y = 227.17
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_405")
obj.X = 96.50
obj.Y = 227.11
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "1"

Set obj = layout.CreateObject(1, "Text_406")
obj.X = 104.47
obj.Y = 227.17
obj.Width = 10.29
obj.Height = 3.29
obj.Content = "Rollover"

Set obj = layout.CreateObject(1, "Text_407")
obj.X = 124.43
obj.Y = 227.11
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "2"

Set obj = layout.CreateObject(1, "Text_408")
obj.X = 132.40
obj.Y = 227.17
obj.Width = 5.80
obj.Height = 3.29
obj.Content = "PSO"

Set obj = layout.CreateObject(1, "Text_409")
obj.X = 147.29
obj.Y = 227.11
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "3"

Set obj = layout.CreateObject(1, "Text_410")
obj.X = 33.98
obj.Y = 231.34
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "6a"

Set obj = layout.CreateObject(1, "Text_411")
obj.X = 40.63
obj.Y = 231.41
obj.Width = 32.10
obj.Height = 3.29
obj.Content = "Social security benefits ."

Set obj = layout.CreateObject(1, "Text_412")
obj.X = 76.18
obj.Y = 231.41
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_413")
obj.X = 83.48
obj.Y = 231.34
obj.Width = 3.97
obj.Height = 3.37
obj.Content = "6a "

Set obj = layout.CreateObject(1, "Text_414")
obj.X = 119.35
obj.Y = 231.34
obj.Width = 3.29
obj.Height = 3.37
obj.Content = "b  "

Set obj = layout.CreateObject(1, "Text_415")
obj.X = 122.65
obj.Y = 231.41
obj.Width = 22.04
obj.Height = 3.29
obj.Content = "Taxable amount ."

Set obj = layout.CreateObject(1, "Text_416")
obj.X = 148.13
obj.Y = 231.41
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_417")
obj.X = 152.37
obj.Y = 231.41
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_418")
obj.X = 156.60
obj.Y = 231.41
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_419")
obj.X = 160.83
obj.Y = 231.41
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_420")
obj.X = 165.06
obj.Y = 231.41
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_421")
obj.X = 172.31
obj.Y = 231.34
obj.Width = 4.08
obj.Height = 3.37
obj.Content = "6b "

Set obj = layout.CreateObject(1, "Text_422")
obj.X = 35.55
obj.Y = 235.57
obj.Width = 1.62
obj.Height = 3.37
obj.Content = "c"

Set obj = layout.CreateObject(1, "Text_423")
obj.X = 40.63
obj.Y = 235.64
obj.Width = 100.93
obj.Height = 3.29
obj.Content = "If you elect to use the lump-sum election method, check here (see instructions)  "

Set obj = layout.CreateObject(1, "Text_424")
obj.X = 143.90
obj.Y = 235.64
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_425")
obj.X = 148.13
obj.Y = 235.64
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_426")
obj.X = 152.37
obj.Y = 235.64
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_427")
obj.X = 156.60
obj.Y = 235.64
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_428")
obj.X = 160.83
obj.Y = 235.64
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_429")
obj.X = 35.55
obj.Y = 239.80
obj.Width = 1.72
obj.Height = 3.37
obj.Content = "d"

Set obj = layout.CreateObject(1, "Text_430")
obj.X = 40.63
obj.Y = 239.87
obj.Width = 122.58
obj.Height = 3.29
obj.Content = "If you are married filing separately and lived apart from your spouse the entire year (see inst.), check here"

Set obj = layout.CreateObject(1, "Text_431")
obj.X = 33.98
obj.Y = 244.04
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "7a"

Set obj = layout.CreateObject(1, "Text_432")
obj.X = 40.63
obj.Y = 244.10
obj.Width = 65.84
obj.Height = 3.29
obj.Content = "Capital gain or (loss). Attach Schedule D if required  "

Set obj = layout.CreateObject(1, "Text_433")
obj.X = 110.04
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_434")
obj.X = 114.27
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_435")
obj.X = 118.51
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_436")
obj.X = 122.74
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_437")
obj.X = 126.97
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_438")
obj.X = 131.20
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_439")
obj.X = 135.44
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_440")
obj.X = 139.67
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_441")
obj.X = 143.90
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_442")
obj.X = 148.13
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_443")
obj.X = 152.37
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_444")
obj.X = 156.60
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_445")
obj.X = 160.83
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_446")
obj.X = 165.06
obj.Y = 244.10
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_447")
obj.X = 172.36
obj.Y = 244.04
obj.Width = 3.19
obj.Height = 3.37
obj.Content = "7a"

Set obj = layout.CreateObject(1, "Text_448")
obj.X = 35.55
obj.Y = 248.27
obj.Width = 1.72
obj.Height = 3.37
obj.Content = "b"

Set obj = layout.CreateObject(1, "Text_449")
obj.X = 40.63
obj.Y = 248.33
obj.Width = 11.13
obj.Height = 3.29
obj.Content = "Check if:"

Set obj = layout.CreateObject(1, "Text_450")
obj.X = 58.20
obj.Y = 248.33
obj.Width = 30.62
obj.Height = 3.29
obj.Content = "Schedule D not required"

Set obj = layout.CreateObject(1, "Text_451")
obj.X = 96.29
obj.Y = 248.33
obj.Width = 45.30
obj.Height = 3.29
obj.Content = "Includes child’s capital gain or (loss)"

Set obj = layout.CreateObject(1, "Text_452")
obj.X = 33.98
obj.Y = 252.50
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "8"

Set obj = layout.CreateObject(1, "Text_453")
obj.X = 40.63
obj.Y = 252.57
obj.Width = 57.50
obj.Height = 3.29
obj.Content = "Additional income from Schedule 1, line 10 ."

Set obj = layout.CreateObject(1, "Text_454")
obj.X = 101.58
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_455")
obj.X = 105.81
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_456")
obj.X = 110.04
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_457")
obj.X = 114.27
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_458")
obj.X = 118.51
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_459")
obj.X = 122.74
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_460")
obj.X = 126.97
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_461")
obj.X = 131.20
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_462")
obj.X = 135.44
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_463")
obj.X = 139.67
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_464")
obj.X = 143.90
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_465")
obj.X = 148.13
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_466")
obj.X = 152.37
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_467")
obj.X = 156.60
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_468")
obj.X = 160.83
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_469")
obj.X = 165.06
obj.Y = 252.57
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_470")
obj.X = 173.17
obj.Y = 252.50
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "8"

Set obj = layout.CreateObject(1, "Text_471")
obj.X = 33.98
obj.Y = 256.73
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "9"

Set obj = layout.CreateObject(1, "Text_472")
obj.X = 40.63
obj.Y = 256.80
obj.Width = 69.52
obj.Height = 3.29
obj.Content = "Add lines 1z, 2b, 3b, 4b, 5b, 6b, 7a, and 8. This is your "

Set obj = layout.CreateObject(1, "Text_473")
obj.X = 110.16
obj.Y = 256.73
obj.Width = 17.55
obj.Height = 3.37
obj.Content = "total income "

Set obj = layout.CreateObject(1, "Text_474")
obj.X = 131.20
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_475")
obj.X = 135.44
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_476")
obj.X = 139.67
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_477")
obj.X = 143.90
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_478")
obj.X = 148.13
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_479")
obj.X = 152.37
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_480")
obj.X = 156.60
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_481")
obj.X = 160.83
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_482")
obj.X = 165.06
obj.Y = 256.80
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_483")
obj.X = 173.17
obj.Y = 256.73
obj.Width = 1.57
obj.Height = 3.37
obj.Content = "9"

Set obj = layout.CreateObject(1, "Text_484")
obj.X = 32.41
obj.Y = 260.97
obj.Width = 3.92
obj.Height = 3.37
obj.Content = "10 "

Set obj = layout.CreateObject(1, "Text_485")
obj.X = 40.63
obj.Y = 261.03
obj.Width = 61.26
obj.Height = 3.29
obj.Content = "Adjustments to income from Schedule 1, line 26 "

Set obj = layout.CreateObject(1, "Text_486")
obj.X = 105.81
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_487")
obj.X = 110.04
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_488")
obj.X = 114.27
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_489")
obj.X = 118.51
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_490")
obj.X = 122.74
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_491")
obj.X = 126.97
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_492")
obj.X = 131.20
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_493")
obj.X = 135.44
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_494")
obj.X = 139.67
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_495")
obj.X = 143.90
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_496")
obj.X = 148.13
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_497")
obj.X = 152.37
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_498")
obj.X = 156.60
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_499")
obj.X = 160.83
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_500")
obj.X = 165.06
obj.Y = 261.03
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_501")
obj.X = 172.38
obj.Y = 260.97
obj.Width = 3.14
obj.Height = 3.37
obj.Content = "10"

Set obj = layout.CreateObject(1, "Text_502")
obj.X = 32.41
obj.Y = 265.02
obj.Width = 4.76
obj.Height = 3.37
obj.Content = "11a"

Set obj = layout.CreateObject(1, "Text_503")
obj.X = 40.63
obj.Y = 265.09
obj.Width = 50.64
obj.Height = 3.29
obj.Content = "Subtract line 10 from line 9. This is your "

Set obj = layout.CreateObject(1, "Text_504")
obj.X = 91.28
obj.Y = 265.02
obj.Width = 30.72
obj.Height = 3.37
obj.Content = "adjusted gross income"

Set obj = layout.CreateObject(1, "Text_505")
obj.X = 121.99
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_506")
obj.X = 126.97
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_507")
obj.X = 131.20
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_508")
obj.X = 135.44
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_509")
obj.X = 139.67
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_510")
obj.X = 143.90
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_511")
obj.X = 148.13
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_512")
obj.X = 152.37
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_513")
obj.X = 156.60
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_514")
obj.X = 160.83
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_515")
obj.X = 165.06
obj.Y = 265.09
obj.Width = 0.78
obj.Height = 3.29
obj.Content = "."

Set obj = layout.CreateObject(1, "Text_516")
obj.X = 171.57
obj.Y = 265.20
obj.Width = 4.76
obj.Height = 3.37
obj.Content = "11a"

Set obj = layout.CreateObject(1, "Text_517")
obj.X = 12.70
obj.Y = 269.65
obj.Width = 117.27
obj.Height = 3.16
obj.Content = "For Disclosure, Privacy Act, and Paperwork Reduction Act Notice, see separate instructions. "

Set obj = layout.CreateObject(1, "Text_518")
obj.X = 136.83
obj.Y = 269.93
obj.Width = 19.07
obj.Height = 2.88
obj.Content = "Cat. No. 11320B "

Set obj = layout.CreateObject(1, "Text_519")
obj.X = 164.07
obj.Y = 269.98
obj.Width = 6.45
obj.Height = 2.88
obj.Content = "Form "

Set obj = layout.CreateObject(1, "Text_520")
obj.X = 170.52
obj.Y = 268.89
obj.Width = 7.84
obj.Height = 4.21
obj.Content = "1040"

Set obj = layout.CreateObject(1, "Text_521")
obj.X = 178.37
obj.Y = 269.93
obj.Width = 0.69
obj.Height = 2.95
obj.Content = " "

Set obj = layout.CreateObject(1, "Text_522")
obj.X = 179.05
obj.Y = 269.98
obj.Width = 24.10
obj.Height = 2.88
obj.Content = "(2025) Created 9/5/25"

